stages:
  - build-and-test
  - benchmark

variables:
  PYTHONUNBUFFERED: "true"
  JVMCI_BIN: /home/gitlab-runner/.local/graal-core/bin/java
  JVMCI_VERSION_CHECK: ignore
  ECLIPSE_EXE: /home/gitlab-runner/.local/eclipse/eclipse

before_script:
  - git submodule update --init

build_and_test_job:
  stage: build-and-test
  tags: [benchmarks, infinity]
  script:
    - ant checkstyle
    - ant eclipseformat-check
    - timeout 5m ant unit-tests som-tests

benchmark_job:
  stage: benchmark
  tags: [benchmarks, infinity]
  allow_failure: true
  script:
    - ant compile
    - rebench -d --without-nice -c --commit-id="$CI_BUILD_REF" --environment="Infinity Ubuntu" --project=SOMns --branch=master super.conf
    - curl -F "file=@codespeed.data" https://file.io
